# Generated by Django 4.2.4 on 2023-08-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_alter_tour_area_code_alter_tour_cat1_alter_tour_cat2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailIntroTravel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heritage1', models.CharField(max_length=1)),
                ('accom_count', models.CharField(max_length=10)),
                ('exp_age_range', models.CharField(max_length=10)),
                ('exp_guide', models.TextField(default='')),
                ('info_center', models.CharField(max_length=30)),
                ('open_date', models.CharField(max_length=30)),
                ('parking', models.CharField(max_length=10)),
                ('rest_date', models.CharField(max_length=30)),
                ('use_season', models.CharField(max_length=30)),
                ('use_time', models.CharField(max_length=30)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_intro_travel', to='main.servicecode')),
            ],
        ),
    ]
