# Generated by Django 4.2.4 on 2023-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_detailintrotravel_info_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrotravel',
            name='info_center',
            field=models.CharField(max_length=500),
        ),
    ]
