# Generated by Django 4.2.4 on 2023-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_detailintrotravel_info_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrotravel',
            name='parking',
            field=models.CharField(max_length=100),
        ),
    ]
