# Generated by Django 4.2.4 on 2023-08-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_detailintrotravel_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrotravel',
            name='accom_count',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detailintrotravel',
            name='exp_age_range',
            field=models.CharField(max_length=50),
        ),
    ]
