# Generated by Django 4.2.4 on 2023-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_detailintrotravel_use_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrotravel',
            name='use_time',
            field=models.CharField(max_length=500),
        ),
    ]
