# Generated by Django 4.2.4 on 2023-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_detailintrotravel_use_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrotravel',
            name='accom_count',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrotravel',
            name='exp_age_range',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='detailintrotravel',
            name='parking',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='detailintrotravel',
            name='rest_date',
            field=models.CharField(max_length=1000),
        ),
    ]
