# Generated by Django 4.2.4 on 2023-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailIntroFest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=30)),
                ('place_info', models.TextField(default='')),
                ('event_homepage', models.URLField(max_length=1024)),
                ('event_place', models.CharField(max_length=40)),
                ('play_time', models.CharField(max_length=30)),
                ('program', models.TextField(default='')),
                ('age_limit', models.CharField(max_length=30)),
                ('spend_time_festival', models.CharField(max_length=30)),
                ('booking_place', models.CharField(max_length=30)),
                ('discount_info_festival', models.CharField(max_length=30)),
                ('event_start_date', models.CharField(max_length=30)),
                ('event_end_date', models.CharField(max_length=30)),
                ('sponsor1', models.CharField(max_length=30)),
                ('sponsor1tel', models.CharField(max_length=30)),
                ('sponsor2', models.CharField(max_length=30)),
                ('sponsor2tel', models.CharField(max_length=30)),
                ('sub_event', models.CharField(max_length=30)),
                ('use_time_festival', models.CharField(max_length=30)),
            ],
        ),
    ]
