# Generated by Django 4.2.4 on 2023-08-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sigungucode_areacode_sigungu_code_and_more'),
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_intro', to='main.servicecode'),
        ),
    ]
