# Generated by Django 4.2.4 on 2023-08-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tour_area_code_alter_tour_cat1_alter_tour_cat2_and_more'),
        ('festival', '0002_alter_detailintrofest_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_intro_fest', to='main.servicecode'),
        ),
    ]
