# Generated by Django 4.2.4 on 2023-08-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicecode_content_type_id_and_more'),
        ('festival', '0003_alter_detailintrofest_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_intro_fest', to='main.tour'),
        ),
    ]
