# Generated by Django 4.2.4 on 2023-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_alter_detailintrofest_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='age_limit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='booking_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='discount_info_festival',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='event_end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='event_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='event_start_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='play_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='spend_time_festival',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor1tel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor2tel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sub_event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='use_time_festival',
            field=models.CharField(max_length=100),
        ),
    ]
