# Generated by Django 4.2.4 on 2023-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_alter_detailintrofest_age_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor1tel',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor2tel',
            field=models.CharField(max_length=500),
        ),
    ]
