# Generated by Django 4.2.4 on 2023-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_alter_detailintrofest_sponsor1tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='use_time_festival',
            field=models.CharField(max_length=500),
        ),
    ]
