# Generated by Django 4.2.4 on 2023-08-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_alter_detailintrofest_use_time_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='event_place',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sponsor2',
            field=models.CharField(max_length=500),
        ),
    ]
