# Generated by Django 4.2.4 on 2023-08-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_alter_detailintrofest_event_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='age_limit',
            field=models.CharField(max_length=500),
        ),
    ]
