# Generated by Django 4.2.4 on 2023-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0009_alter_detailintrofest_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailintrofest',
            name='booking_place',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='discount_info_festival',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='play_time',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='spend_time_festival',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detailintrofest',
            name='sub_event',
            field=models.CharField(max_length=500),
        ),
    ]
