# Generated by Django 4.2.4 on 2023-08-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('sigungucode', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('sigunguname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maincode', models.CharField(max_length=40)),
                ('mainname', models.CharField(max_length=40)),
                ('midcode', models.CharField(max_length=40)),
                ('midname', models.CharField(max_length=40)),
                ('subcode', models.CharField(max_length=40)),
                ('subname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr1', models.TextField(default='')),
                ('addr2', models.TextField(default='')),
                ('firstimage', models.URLField(max_length=1024)),
                ('firstimage2', models.URLField(max_length=1024)),
                ('cpyrhtDivCd', models.CharField(max_length=40)),
                ('mapx', models.CharField(max_length=50)),
                ('mapy', models.CharField(max_length=50)),
                ('mlevel', models.CharField(max_length=20)),
                ('modifiedtime', models.CharField(max_length=50)),
                ('tel', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('areacode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AreaCode', to='main.areacode')),
                ('cat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat1', to='main.servicecode')),
                ('cat2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat2', to='main.servicecode')),
                ('cat3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat3', to='main.servicecode')),
                ('contentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContentId', to='main.servicecode')),
                ('contenttypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContentTypeid', to='main.servicecode')),
                ('sigungucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SigunguCode', to='main.areacode')),
            ],
        ),
    ]
