# Generated by Django 4.2.4 on 2023-08-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacode',
            old_name='sigungucode',
            new_name='sigungu_code',
        ),
        migrations.RenameField(
            model_name='areacode',
            old_name='sigunguname',
            new_name='sigungu_name',
        ),
        migrations.RenameField(
            model_name='servicecode',
            old_name='maincode',
            new_name='main_code',
        ),
        migrations.RenameField(
            model_name='servicecode',
            old_name='mainname',
            new_name='main_name',
        ),
        migrations.RenameField(
            model_name='servicecode',
            old_name='midcode',
            new_name='mid_code',
        ),
        migrations.RenameField(
            model_name='servicecode',
            old_name='midname',
            new_name='mid_name',
        ),
        migrations.RenameField(
            model_name='servicecode',
            old_name='subcode',
            new_name='sub_code',
        ),
        migrations.RenameField(
            model_name='servicecode',
            old_name='subname',
            new_name='sub_name',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='areacode',
            new_name='area_code',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='contentid',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='contenttypeid',
            new_name='content_type_id',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='firstimage',
            new_name='first_image',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='firstimage2',
            new_name='first_image2',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='modifiedtime',
            new_name='modified_time',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='sigungucode',
            new_name='sigungu_code',
        ),
    ]
