# Generated by Django 4.2.4 on 2023-08-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sigungucode_areacode_sigungu_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='area_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_area', to='main.areacode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_cat1', to='main.servicecode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_cat2', to='main.servicecode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_cat3', to='main.servicecode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='main.servicecode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_type', to='main.servicecode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sigungu_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_sigungu', to='main.areacode'),
        ),
    ]
