# Generated by Django 4.2.4 on 2023-08-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tour_content_id_detailinfo_detailcommon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecode',
            name='content_type_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='detailcommon',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailCommon', to='main.tour'),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailInfo', to='main.tour'),
        ),
        migrations.AlterField(
            model_name='detailinfo',
            name='content_type_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='area_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='main.servicecode'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content_type_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='sigungu_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='main.areacode'),
        ),
    ]
