# Generated by Django 4.2.4 on 2023-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicecode_content_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcommon',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
