# Generated by Django 4.2.4 on 2023-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_detailcommon_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcommon',
            name='tel_Name',
            field=models.CharField(max_length=500),
        ),
    ]
