# Generated by Django 4.2.4 on 2023-08-12 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_detailcommon_tel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='like_users',
            field=models.ManyToManyField(related_name='like_tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
